FD001:
  n_clusters: 1
  max_rul: 125
  window_size: 30     
  n_train_engines: 100
  n_test_engines: 100
  fault_modes: [fan]
  single_condition: true
  alert_thresholds:
    critical_prob_20: 0.90
    warning_prob_50: 0.75
    monitor_prob_50: 0.50
  vae_hidden_dim: 64
  vae_latent_dim: 16
  vae_num_layers: 1
  vae_beta: 0.0
  vae_epochs: 100
  vae_patience: 10
  vae_lr: 0.001
  vae_batch_size: 256
  vae_healthy_rul_threshold: 80
  vae_beta_warmup_fraction: 0.0

FD002:
  n_clusters: 6
  max_rul: 125
  window_size: 50     
  n_train_engines: 260
  n_test_engines: 259
  fault_modes: [fan]
  single_condition: false
  alert_thresholds:
    critical_prob_20: 0.90
    warning_prob_50: 0.75
    monitor_prob_50: 0.50
  vae_hidden_dim: 64
  vae_latent_dim: 32        # larger latent space for 6-condition complexity
  vae_num_layers: 1
  vae_beta: 0.0
  vae_epochs: 100
  vae_patience: 10
  vae_lr: 0.001
  vae_batch_size: 256
  vae_healthy_rul_threshold: 80
  vae_beta_warmup_fraction: 0.0

FD003:
  n_clusters: 1
  max_rul: 125
  window_size: 30     
  n_train_engines: 100
  n_test_engines: 100
  fault_modes: [HPC]
  single_condition: true
  alert_thresholds:
    critical_prob_20: 0.90
    warning_prob_50: 0.75
    monitor_prob_50: 0.50
  vae_hidden_dim: 64
  vae_latent_dim: 16
  vae_num_layers: 1
  vae_beta: 0.0
  vae_epochs: 100
  vae_patience: 10
  vae_lr: 0.001
  vae_batch_size: 256
  vae_healthy_rul_threshold: 80
  vae_beta_warmup_fraction: 0.0

FD004:
  n_clusters: 6
  max_rul: 125
  window_size: 50     
  n_train_engines: 248
  n_test_engines: 249
  fault_modes: [HPC, fan]
  single_condition: false
  alert_thresholds:
    critical_prob_20: 0.60
    warning_prob_50: 0.65
    monitor_prob_50: 0.40
  vae_hidden_dim: 64
  vae_latent_dim: 32 
  vae_num_layers: 1
  vae_beta: 0.0
  vae_epochs: 100
  vae_patience: 10
  vae_lr: 0.001
  vae_batch_size: 256
  vae_healthy_rul_threshold: 80
  vae_beta_warmup_fraction: 0.0